### ISSUE TITLE
Bug in the spglib

### ISSUE THREAD

**Issue by grigorijo** [dlonie/XtalComp#8]
Dear XtalComp developer(s). I noticed that the version of spglib that XtalComp uses contains a bug that produces a **segfault** when spg_get_international function is called with large Cartesian tolerance (cartTol in the XtalComp code and symprec in the spglib code).

To see the bug, just clone the latest XtalComp version, modify the cartTol in the simpleCase() (line 58 in test.cpp of XtalComp) function to for example 5.0 (or any number bigger than about 1.5). You will see the **segfault** immediately.

This bug is fixed in the latest version of spglib  1.9.9 (even earlier version starting from 1.9.1). Instead of segfault it now writes some message like this:

"An invalid spg was detected by spglib for cell 1".

I was able to simply overwrite the spglib library of XtalComp with the latest git clone of spglib source files, trivially modifying the CMakeLists.txt file in the spglib library correspondingly (minus some files, plus some files) and it just worked. 

I think it would be great if the latest git clone of XtalComp had the updated version of the spglib where segfault bug is fixed.

I appreciate your time to look into this issue.

Sincerely,
Grigory

**Comment by alliepiper** [comment]
Thanks for the report! I'll take a look at this soon.

**Comment by alliepiper** [comment]
Oddly enough, I couldn't replicate the segfault. But either way, spglib has been updated both in master and on the xtalcomp web interface (http://xtalopt.openmolecules.net/xtalcomp/xtalcomp.html).

Thanks again for the report!
